INSERT INTO `config_settings` (`id`, `config_category_id`, `config_constant`, `description`, `config_value`, `created_by`, `created_at`, `updated_by`, `updated_at`) VALUES
(null, 1, 'C_META_DESC', 'Home Page Meta Description', 'Beeryde', '1', now() , '1', now()),
(null, 1, 'C_META_KEY', 'Home Page META Keywords', 'Beeryde', '1', now() , '1', now()),
(null, 1, 'C_SITENAME', 'Site Name', 'Beeryde', '1', now() , '1', now()),
(null, 1, 'C_SITEURL', 'Site URL', 'http://www.beeryde.com', '1', now() , '1', now()),
(null, 2, 'C_MIME_VERSION', 'MIME Version', 'MIME-Version: 1.0\\r\\n', '1', now() , '1', now()),
(null, 2, 'C_CONTENT_TYPE', 'Content Type', 'Content-type: text/html', '1', now() , '1', now()),
(null, 2, 'C_CHARSET', 'Charset', 'charset=iso-8859-1\\r\\n', '1', now() , '1', now()),
(null, 2, 'C_CS_EMAILID', 'Contact Email ID', 'contact@beeryde.com', '1', now() , '1', now()),
(null, 2, 'C_BOUNCE_EMAILID', 'Email ID where all bounced emails should go', 'nileshpangul4u@gmail.com', '1', now() , '1', now()),
(null, 3, 'C_CS_PHONE', 'Customer Service Phone Number', '(800) 123 - 4568', '1', now() , '1', now()),
(null, 3, 'C_SALES_PHONE', 'Sales Phone Number', '(800) 123 - 4567', '1', now() , '1', now()),
(null, 2, 'C_REPLY_EMAILID', 'Reply To Email ID', 'customerservice@beeryde.com', '1', now() , '1', now()),
(null, 4, 'C_RECORDS_PER_PAGE', 'Records Per Page', '10', '1', now() , '1', now()),
(null, 4, 'C_LINKS_PER_PAGE', 'Page Links Per Page Eg. 1 2 3 4 5', '5', '1', now() , '1', now()),
(null, 5, 'C_DATEFORMAT', 'Date Display Format with Time', 'D d F y g:i A', '1', now() , '1', now()),
(null, 5, 'C_ONLYDATE', 'Only Date without Time', 'jS F Y', '1', now() , '1', now()),
(null, 6, 'C_ALLOWED_EXTNS', 'File Extensions Allowed', '.txt, .doc, .xls, .rtf, .pdf, .jpg, .gif, .zip', '1', now() , '1', now()),
(null, 6, 'C_MAX_SIZE', 'Max File Size Allowed (in bytes)', '2000000', '1', now() , '1', now()),
(null, 6, 'MGT_IMG_HEIGHT', 'Add/Edit Managment (image height)', '120', '1', now() , '1', now()),
(null, 6, 'MGT_IMG_WIDTH', 'Add/Edit Managment (image width)', '100', '1', now() , '1', now()),
(null, 1, 'C_DEFAULT_CURRENCY', 'Default Currency', '$', '1', now() , '1', now()),
(null, 1, 'ADMIN_USER_NAME_MIN_LENGTH', 'Admin Username Minimum Length', '6', '1', now() , '1', now()),
(null, 6, 'C_ALLOWED_IMAGE_EXTNS', 'Image File Extensions Allowed', 'gif|jpg|jpeg|png', '1', now() , '1', now()),
(null, 1, 'ADMIN_PASSWORD_MIN_LENGTH', 'Admin Password Minimum Length', '6', '1', now() , '1', now()),
(null, 6, 'C_ADMIN_THUMB_WIDTH', 'Admin Thumbnail Image Width', '92', '1', now() , '1', now()),
(null, 6, 'C_ADMIN_THUMB_HEIGHT', 'Admin Thumbnail Image Height', '100', '1', now() , '1', now()),
(null, 6, 'C_NEWS_BANNER_WIDTH', 'News Banner Width', '630', '1', now() , '1', now()),
(null, 6, 'C_NEWS_BANNER_HEIGHT', 'News Banner Height', '181', '1', now() , '1', now()),
(null, 6, 'C_IMAGE_THUMB_WIDTH', 'Thumbnail Image Width', '140', '1', now() , '1', now()),
(null, 6, 'C_IMAGE_THUMB_HEIGHT', 'Thumbnail Image Height', '0', '1', now() , '1', now()),
(null, 1, 'LATITUDE', 'Latitude', '18.519357360080246', '1', now() , '1', now()),
(null, 1, 'LONGITUDE', 'Longitude', '73.84225847266839', '1', now() , '1', now()),
(null, 6, 'ATTACHMENTLIMIT', 'Attachment Limit', '5', '1', now() , '1', now()),
(null, 6, 'GALLERYLIMIT', 'Gallery Select Limit', '20', '1', now() , '1', now()),
(null, 1, 'C_SESSION_LIFETIME_MINUTES', 'set session life time for admin site', '30', '1', now() , '1', now());